name: dorm_of_decents
description: "A comprehensive bachelors flat management application built with
  Flutter. Track meals, expenses, settlements, and manage user activities in
  shared living spaces."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.10.1

dependencies:
  animations: ^2.1.1
  blur: ^4.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.0
  grid_background: ^0.0.1
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.9.1
  timeago: ^3.7.1
  toastification: ^3.0.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700

    - family: Crimson Text
      fonts:
        - asset: assets/fonts/CrimsonText-Regular.ttf
        - asset: assets/fonts/CrimsonText-Bold.ttf
          weight: 700
